### ISSUE TITLE
Could you possibly use an api call for the already found lab caches

### ISSUE THREAD

**Issue by jamesanderson16** [mirsch/lab2gpx#11]
Is it possible to add a feature to use an api call instead of copy and pasting sorce code as it is bacically impossible to do on an iPhone without using an external source (e.g. a computer to copy the source code and then to email it to yourself which may have caused my last issue)

thanks

James0116

**Comment by mirsch** [comment]
There is no official API to access data of Lab caches. All API calls used to fetch the data are discovered by tracking traffic of the original Adventure Labs App.
Since there is no official API and the tool runs on the server side, we cannot (securely) log in and access user-specific data.
I know that this is very cumbersome, but unfortunately there is technically no (safe) way to get the data in the browser except via copy & paste. Please have a look at https://github.com/mirsch/lab2gpx/issues/8#issuecomment-760430999 how to get this to work on the iPhone.

**Comment by PlasmaWave** [comment]
Copying the script from a PC then e-mailing it to yourself, or say via a Notepad file in Dropbox, didn't work for me. Only accessing mirsch's javascript directly via the given URL then wiping over and copying&pasting worked. I am using an iPhone 7.

The process of creating the bookmarklet appeared very complicated when I did it, i.e. before mirsch added his step-by-step instructions (https://github.com/mirsch/lab2gpx/issues/8#issuecomment-760481595) but I did manage ok. However following the author's instructions, added shortly after I did it, works a treat. Once the bookmarklet has been created, the process of displaying the source code and copying&pasting into the search box is quick and easy. Creating the bookmarklet is a one off task and is called up as and when you need it. I actually created the same bookmark on the PC since the copy&paste part is so much easier using it.

Persevere, it's well worth it.

**Comment by jamesanderson16** [comment]
@mirsch 

could you possibly add a direct link to comment 8 on the webpage with a note so people know about the issue and how to fix it possibly please

thanks

James0116

**Comment by SD1313** [comment]
> There is no official API to access data of Lab caches. All API calls used to fetch the data are discovered by tracking traffic of the original Adventure Labs App.
> Since there is no official API and the tool runs on the server side, we cannot (securely) log in and access user-specific data.
> I know that this is very cumbersome, but unfortunately there is technically no (safe) way to get the data in the browser except via copy & paste. Please have a look at [#8 (comment)](https://github.com/mirsch/lab2gpx/issues/8#issuecomment-760430999) how to get this to work on the iPhone.

The API is available here: https://labs-api.geocaching.com/swagger/ui/index

**Comment by mirsch** [comment]
We would need an API Key but since the API is not officially open to developers we will not get such a key. I'm sure as soon as the API is open it's implemented in several geocaching apps, so we don't need this tool anymore.
