### ISSUE TITLE
Add option to mark completed Lab Stages as 'Found'

### ISSUE THREAD

**Issue by PlasmaWave** [mirsch/lab2gpx#8]
Would it be possible to provide a selectable option for the user to have completed Lab Stages indicated as 'Found' in the gpx?

The GSAK 'ImportAdventureLabs' macro achieves this by providing the user with the option to log into geocaching.com before running the macro ... maybe too difficult via the browser 'app'?

Would be a really useful option if it were possible. 'Found' Labs can be filtered within the user's Geocaching App, so provides more flexibility.

**Comment by mirsch** [comment]
there is now a new checkbox below the field for your finds source.
This will not fetch all your finds but mark the caches included in the current gpx as found.
If you want a 'my finds' gpx for labs I think this should be a separate tool.

**Comment by travels4jack** [comment]
Can't see that field ?
Where exactly can it be found ? 
Has there been a newer version of the macro recently ?

BTW If this helps:
I was also looking to mark my finds as I complete the Labs.
Found the easy solution to just delete that very Lab just found. Keeps my GPX clean of already found Labs and only appear the ones to be found. Suits me extremely well.
Bottom line you can delete each Lab marker individually.
- click on the Lab to get the description screen
- click the top right "..." button 
- from the scrll down menu select the very first option "DELETE" (in red font)
- and you are done !! the Lab disappears from your map.

**Comment by PlasmaWave** [comment]
I can see the new tick box ok but the resulting gpx does not mark my completed Labs/stages. I refreshed (again) the browser a second time and re-ran it, but still my 'Found' Labs show no marks that I can see ... what should we see? A smiley yellow face or other icon change or a simple flag ticked?

A separate tool for MyFinds (Labs) would be useful but the present gpx does still need the option to exclude or mark 'Found' Labs ... I am still struggling when using the phone, which will be the main use for me, to get the source code to work (works fine on PC browser).

Re travels4jack - I do not necessarily want to delete my 'Found' Labs from the gpx, rather have the choice of filtering from within my usual app (L4C). I do not want to manually mark & delete my 'Found' Lab stages each time I run the script when running it on the phone.

**Comment by travels4jack** [comment]
Re PlasmaWave:
May have misunderstood, 'cause on one side you highlight that your GPX does not mark your completed Labs/stages and on the other hand you are not sure you want to delete your "Founds"

I am running on Cachly and had no issue with already found Labs/stages since the last update of the script.

Not sure how l4C works but I generate the gpx from on my desktop
- Easy to modify origin point, radius and # of caches here: https://gcutils.de/lab2gpx/
-  Easy to cut and paste the source code from here: https://labs.geocaching.com/logs  (right click - source code copy and paste entire text)
- download gpx (extract it from the zip file, store it on dropbox
- open Cachly and import gpx directly from dropbox and save it as an offline list
- Works extremely well for me and can't praise more the other for providing us this feature.
- Was really tired of switching grom Cachly to AdLabs and vice versa. With the high number of Labs with quite a lot of overlaping stages between Labs that has considerably made my life easier. 
- There surely could be other enhancements but this is already luxury compared to nothing.

**Comment by PlasmaWave** [comment]
Hi T4J ... clearly my poor explanation and intertwinning two features. I also agree this script is fantastic and said so in my first post.

If you read back through a couple of my posts, I also have no problem when generating the gpx in my desktop PC browser ... my completed Labs are excluded when the source code is added. The problem is when running the script from my phone browser (my main intended use), where in iOS you do not directly have the option to view & copy the source code - copying the source code derived from the desktop via a text file didn't work, but misch mentioned how he manages to get it working ok on the phone browser (using a 'bookmarklet') and is trying to educate me, though I'm still struggling at present. So this problem is separate to the enhancement I was requesting, rather this is about the fact that I cannot get the exisitng feature of excluding completed Labs to work when running it from the phone's browser.

Separate 'subject' to above issue, I requested to mark completed Labs as found, hence misch added the tickbox at the bottom of the search page that was intended to mark completed Labs as found, but doesn't seem to work for me on initial testing.

Regarding the question of me not wishing to delete completed Labs, I was saying I do not want to MANUALLY do this everytime the script is run. If completed Labs are marked as 'Found' in some way (i.e. my requested enhancement), then the caching App (Looking4Cache and Cachly) will filter in or out the found Labs. 

Hope the two subjects intertwinned are a little clearer now.

**Comment by mirsch** [comment]
@travels4jack 
>     * download gpx (extract it from the zip file, store it on dropbox
you do not need to extract it. Cachly can read the zip file. 
On my phone Cachly crashes if I want to read unzipped GPX that's why it's zipped :)

**Comment by mirsch** [comment]
@PlasmaWave 
Mark as found only works if you paste the source of your finds. If you don't tick the box the caches are excluded from GPX if you check the box the caches are marked as found in the GPX. I've tried this using Cachly and the Caches are shown as smilies on the map.

To get it to work on the phone, you can either save the source of your finds in a text file on the computer or use a bookmarklet in Safari to get the source live from the site.
I don't know why the file is not working from the PC. Please post your source in this form so that I can see what's coming up: https://gcutils.de/lab2gpx/found.php

Regarding Bookmarklets:
Have a look at this site: https://appletoolbox.com/how-to-view-webpage-html-source-codes-on-ipad-iphone-no-app-required/
It explains how to do it step by step.
If it comes to copy the Javascript source for the bookmarklet (the text starting with javascript:) you may want to use my code instead as mentioned in https://github.com/mirsch/lab2gpx/issues/4 it's stored at https://gist.github.com/mirsch/41e2a152ba2c1e50360658925ed82b47 (there is also 1 line starting with javascript:
The difference is that my code packs the source in a text area and all of the text is already selected if you touch the textarea. Otherwise it is a pain to mark the entire text in Safari.

I know that all of this is very cumbersome, but unfortunately there is technically no way to get the data in the browser except via the copy & paste detour.

**Comment by PlasmaWave** [comment]
[PW Completed Labs Code at 2021-01-14.txt](https://github.com/mirsch/lab2gpx/files/5816820/PW.Completed.Labs.Code.at.2021-01-14.txt)

mirsch ... have pasted the text file contents into your form and tried to attach here too.

The recommended webpage is one of those I have been reading, but the bookmark option shown on their phone screen shot is not available on mine. Attached is my screen. Will look more carefully at the webpage and your last post.

Once I understand what to do it's not a problem and worthwhile. Also anything new is interesting!

![IMG_4276 1](https://user-images.githubusercontent.com/72853430/104645795-7822b600-56a7-11eb-90fd-f7f136f53f8d.PNG)

**Comment by mirsch** [comment]
@PlasmaWave 
I've removed the screenshot and file because it may contain personal data.
Your file and also the uploaded source looks good. I need to have a closer look at it. Can you give me the coordinates you used to test?

I try to explain how to use this bookmarklet stuff ;)
1. Create a bookmark (of any page - it dosn't really matter, it's just because there is no other way to create a new bookmark)
2. Edit the bookmark you just created. In Safari tap the book icon at the bottom, search for the bookmark you just created, tap and hold and select edit from the popup. There are 2 lines the first is the name of the page you just bookmarked and the second is the url of that page http://...
3. change the name to some thing related to the bookmarklet you want to create e.g. 'view source'
4. change to url to the code provided in the gist (javascript:...)
5. You have now a bookmark called 'view source' and the url is javascript:...

To use this bookmarklet go to https://labs.geocaching.com/logs and login. Now tap on bookmarks (the book icon on the bottom) to get a list of your bookmarks click you 'view source' bookmark and a new page should open showing the source of your page in an textarea.

**Comment by PlasmaWave** [comment]
mirsch ... yes thanks for removing the attachments.

Once I understood how/where to use your code, the recommended website instructions worked fine. Followed the steps and yippee hooray the Ad Lab script now works exactly how I was hoping for. Once the gpx zip file has been imported into L4C, it's perfect ... can filter my completed Labs to display them or exclude depending on the need. Must document all this before I forget, in case phone needs changing etc.

Many thanks for your kind help and for creating a superb asset ...

**Comment by mirsch** [comment]
@PlasmaWave 
nice to hear it works now.

**Comment by PlasmaWave** [comment]
Our posts crossed ... had just finished successful testing and writing above when yours came through. Co-ords for gpx I used were: 52.823701, -1.187269. Am using various radius and number caches, usually 25/25 or 250km & 500 Labs.
