### ISSUE TITLE
Some Labcaches returned in GPX despite beeing found and included on the finds page (renamed stages?)

### ISSUE THREAD

**Issue by palzkillm** [mirsch/lab2gpx#83]
Hello,

since maybe two to three weeks now, I stumble across the issue, that completed labcache stages reappear in the GPX returned by lab2gpx, although the set is marked as completed in the My Finds HTML.
I looked into the My Finds HTML and the GPX returned by lab2gpx, and I think the issue might be, that the labcache stages have been renamed.

It's quite easy to see on this one: **/Adventures/Details/ce0e6456-a14d-4605-b3b8-bcf2d2d28f11 - Historisch und aktuell: Museen in Hamburg**
In the My Finds HTML, the following are returned as found:

- Stage 1: Deutsches Zusatzstoffmuseum
- Stage 2: Hamburger Schulmuseum
- Stage 3: 2. Spicy&#180;s Gew&#252;rzmuseum
- Stage 4: 4. Mineralogisches Museum Hamburg
- Stage 5: 5. Geologisch-Pal&#228;ontologisches Museum Hamburg

After processing, lab2gpx returns to me as unfound:

- Historisch und aktuell: Museen in Hamburg : S1 1. Deutsches Zusatzstoffmuseum
- Historisch und aktuell: Museen in Hamburg : S3 3. Hamburger Schulmuseum

Others I could identify:
**/Adventures/Details/b133a066-5ef0-4f8c-bf09-b19ddebfa56c - &#196;lteste Pfarrkirche HH - Oldest parish church HH**
All 5 stages

**/Adventures/Details/2efdef59-6dcd-4407-8c5f-2e5b404a3b4e - Tour am und im Flughafen Hamburg Airport**
All 5 stages

The issue seems to be rising, the "Tour am und im Flughafen Hamburg Airport" one was not an issue a week ago, but is now.

Attachements:

[labs2gpx.zip - Original output from the tool](https://github.com/mirsch/lab2gpx/files/8933142/labs2gpx.zip)
[my_finds.zip - Original my finds HTML output](https://github.com/mirsch/lab2gpx/files/8933185/my_finds.zip)

**Comment by mirsch** [comment]
Unfortunately there is no unique identifier for the stage in the source of the "found" page. That's why I compare the name of stage to the stages found in the API response to make sure all stages are found. I did not know that name changes are not reflected to the "found" page. 
But if we just check for the UUID of the Lab it will also mark incomplete Labs as found. (See https://github.com/mirsch/lab2gpx/issues/86#issuecomment-1181714776)
This is not what I would expect. If I've found only 3 of 5 stages I do not want to mark the Lab as found.
Any ideas how to solve this?

**Comment by palzkillm** [comment]
Since I don't know the API output, only guesswork from my end:

 - Each stage has a unique background image URL. Not sure wether that is changeable as well, but worth a shot trying to use that as a UUID
 - You could try and compare the number of solved stages vs. the number of total stages from the API. If the my finds page returns 5 finds, and the API returns a total of 5 stages, it's found. Yes, that leaves open the case of renamed stages for uncompleted adventures - but it's better than the current status.
 - Is there maybe something like an update date in the API? Could compare that with the created date?
 - You could proactively communicate it to the users, and leave it to them to decide: Exclude started adventures, or not?
 - You could create the possibility to list UUIDs for adventures with open/unfound stages, and by that, help the user create their personal exclude list more easily - took me about an hour parsing the HTML and the list to create my exclude list, it would be MUCH quicker, if the tool just lists all UUIDs with a comment of the series and maybe the number of found stages.

Like I said before - only guesswork, since I don't know what the API actually provides.

**Comment by SamHenkel** [comment]
> only guesswork, since I don't know what the API actually provides

Read the documentation and you will know. ;-)
https://labs-api.geocaching.com/swagger/ui/index#/

**Comment by mirsch** [comment]
> Read the documentation and you will know. ;-) https://labs-api.geocaching.com/swagger/ui/index#/

did you notice „SearchV4“ API Call has a „ CallingUserPublicGuid“ parameter? Looks like this works without login. If this is the case we could use all the filters available in the App. No more copy&paste and parsing source.

**Comment by itommyjay** [comment]
Hello,
I see that this issue seems to already be open so I am commenting here instead of opening a new thread. 

I have noticed that roughly since mid-July, the function "Exclude your finds" stopped working. When I paste the entire source code into the form, I still get a GPX output with lab caches which are found. I do not understand the programming so I do not know what the above comments mean, but I just wanted to say that this is also an issue for me. I live in a city which has over a thousand labs, and my account has 940+ lab finds, so I don't know which specific ones they are, if there's a pattern etc. I do know that over the past few months I have many times opened the link to the adventure lab from the GPX file only to find out that the lab is already found/answers.

Tommy

**Comment by edgarbriggs** [comment]
Same problem here, some found lab stations always re-appear, even if finds were excluded. A solution to this problem would be highly appreciated.

**Comment by Rhoenbussard** [comment]
I have the same problem. My download shows all found labcaches. I didn't found a way to exlude the solved labs.
Is there a solution or a workaround for this problem?

**Comment by jmarlman** [comment]
I  have the same problem.  There is one alc with 5 location and  is found and is listed as found but the it is not being excluded  when I execute the program and download the results.     This problem seems to be going on for over a year but not many new comment that it is still occurring.  Is this going to be fixed or is there a solution.

**Comment by mirsch** [comment]
new version using api v4 is online. no need for copy & paste anymore.
neue Version mit API V4 ist online. Kein kopieren & einfügen mehr notwendig.
