### ISSUE TITLE
removed award messages/Tagebucheinträge entfernt

### ISSUE THREAD

**Issue by mirsch** [mirsch/lab2gpx#88]
[german version below]

I've been asked to remove the award messages from time to time. 
Back then I decided not to change it.

Why?
It's a conceptual issue in Groundspeak's API.
When calling the Adventure Lab via the public API, the journal entries (award message and image) are delivered BEFORE the answer is entered.
Groundspeak could simply prevent this by only sending the award information AFTER the correct answer was entered.
Leaving the message out here would only obfuscate the problem, not fix it. Similar tools can continue to expose the award messages.

For me it's a dilemma:
As a programmer I don't want to hide such problems, it should be visible and make it clear to everyone that no "secret" information should be included in the awards.
Of course, as a gamer/geocacher, I don't like to actively support cheating.

To be honest, I haven't actively looked into the tool for a while, nor if and how anyone other than myself is using it.
I just saw in the traffic logs that it's probably being used more than I thought.
And most users will probably not care much about my original intention of issuing the awards, namely to point out a problem in the API.

I have therefore changed my mind: From now on, the award information is no longer included.

---

Ich wurde ein paar mal gebeten, die Journaleinträge/Awards zu entfernen. 
Damals hatte ich beschlossen das nicht zu tun.

Warum?
Es ist ein konzeptionelles Problem in der API von Groundspeak.
Beim Aufruf des Adventure Labs über die öffentliche API werden die Journaleinträge (Awardtext und -Bild) bereits ausgeliefert, BEVOR die Antwort eingegeben wird.
Groundspeak könnte dies einfach verhindern, indem die Award-Informationen erst NACH Eingabe der richtigen Antwort gesendet werden.
Wenn wir die Awards hier nicht ausgeben, wird das Problem nur versteckt, aber nicht behoben. Ähnliche Tools können die Journaleinträge weiterhin anzeigen.

Für mich ist es eine Zwickmühle:
Als Programmierer möchte ich solche Probleme nicht verschweigen, es sollte sichtbar sein und jedem klar machen, dass die Journaleinträge keine „geheimen“ Informationen enthalten sollten.
Als Gamer/Geocacher möchte ich natürlich Cheaten nicht aktiv unterstützen.

Um ehrlich zu sein, habe ich mich seit einiger Zeit nicht mehr aktiv mit dem Tool befasst, auch nicht, ob und wie jemand das außer mir selbst benutzt.
Ich habe gerade in den Access Logs gesehen, dass es wahrscheinlich häufiger verwendet wird, als ich dachte.
Und den meisten Benutzern wird meine ursprüngliche Intention die Awards auszugeben, nämlich auf ein Problem in der API hinzuweisen, ziemlich egal sein.

Daher habe ich meine Meinung geändert: Ab sofort sind die Journaleinträge nicht mehr enthalten.

---

refs #87 #17

**Comment by Skinoku** [comment]
So sad you decided to to such.
It could also have many positive use cases.
:(

**Comment by mirsch** [comment]
> ... It could also have many positive use cases. :(

name one, which doesn't involve cheating

**Comment by Skinoku** [comment]
When I go caching, I try to avoid using my phone to try "disconnecting" from the regular world and get in touch with what's around me.
I usually use my GPS as sole mean for searching caches. When I reach the steps of the AL I write on a piece of paper my answers and then log them at home altogether.
Award messages in this case are useful, for example because they would allow me to discover the location of a bonus cache and search for it before having to insert all the answers into the app and come back another day.
I understand the reasons why you removed such feature from the software and if you think it was abused keep it like that, also if it is a bit of a shame.
Thanks and best wishes

**Comment by mirsch** [comment]
> ... I write on a piece of paper my answers and then log them at home altogether. Award messages in this case are useful, for example because they would allow me to discover the location of a bonus cache and search for it before having to insert all the answers into the app ...

so you use fake gps to enter the answer and find the bonus even before you know your answers are correct.
sounds like cheating.

**Comment by Skinoku** [comment]
I do not agree. Cheating for me is logging ALs from the armchair.
I can buy guns, but is up to me deciding to use them in a shooting range or start killing souls on the road.
I think that should be up to people deciding what to do with the info they have, what is right and what is wrong.
This is your software, I respect your decision also if I don't share it.
Thank you for ur time.
Best wishes

**Comment by domotic-fr** [comment]
I do the same as @Skinoku. I don't think it is cheating. If one day I don't find all stages of a lab, I won't log the bonus.
Without the award information, we can't visit the bonus (when you are on a road trip, you won't got twice to the same place), and the owner may think that we just validated the stages from home.

I see the bonus as an extra stage of the lab cache, its just like having the information for all stages of a linear lab. This is another big help of your tool to organize a trip, especially when you have several linear labs within the area you are visiting. Would you say we are cheating if we visit the stages in a different order than the one set by the owner?

But you don't only have advantages to be offline, you look for all answers, even if the owner offers 4 possible responses...

There are now 10 forks, it would be nice if someone who puts another server (with the award messages) would share the URL.

Thanks for providing this lab2gpx tool.

**Comment by tweezerman** [comment]
Just came across this.  Its a shame that the award message option has been disabled I can understand how it was used to cheat and I really dont get why anyone would need to do that but some people are very strange.

Even though when I created my GPX files I chose to keep the award message I rarely used it as for me all I needed from this tool was all the locations of labs in one place so I could pick them up as I passed.  

The only time I actually used the award message was for a Lab in London where the answer was obscure and many of us doing the stage tried many different answers that were visible at that waypoint all were wrong until another cacher said have you seen then the award message?  The award message showed a picture of the plaque we was suppose to be looking at which was a few metres around the corner, but from seeing that picture of the plaque I was able to find the correct answer at the stage.  This isn't cheating but using the tool to help complete the task which I am sure the creator wanted.  I have since come across a few similar where if the award message was available I could have used it to help guide me to the answer.
Yes messages and feedback has and was sent/left to the setters of the labs explaining the issues around getting the right answer to the stages.

That said though I would be interested in knowing what other tools are around that do what Labs2GPX do as I have yet to find one

**Comment by obfuscoder** [comment]
As far as I can see, the current groundspeak API to fetch the details for ALs does not contain the answers anymore - at least this is the case for the API endpoint used by the AL app.

The API is now designed to provide a hash for the answer to the client for each stage. The client will ask the user to provide an answer and the answer is hashed as well. If both hashes match, the client will send the answer in plain text to the server and the server will validate it again before responding with the answer details.

The server will mark a stage as completed for a user only after giving the correct answer. When fetching the details of a AL via API with an access token tied to a user who already completed some or all of the stages of this AL, the response will contain the answer details for the completed stages.
